apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-aspnetcore-deployment
spec:
  selector:
    matchLabels:
      app: docker-aspnetcore-pod
  template:
    metadata:
      labels:
        app: docker-aspnetcore-pod
    spec:
      containers:
      - name: docker-aspnetcore-container
        image: deepak01.azurecr.io/docker-aspnetcore:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
